### ISSUE TITLE
Build error on ubuntu

### ISSUE THREAD

**Issue by dhruvbird** [zpao/spidernode#7]
$ uname -a
Linux ubuntu 2.6.38-8-generic #42-Ubuntu SMP Mon Apr 11 03:31:50 UTC 2011 i686 i686 i386 GNU/Linux
- export CC=gcc
- export CXX=g++
- cd /home/dhruvbird/projects/spidernode/deps/mozjs/js/src
- autoconf213
  /bin/sh: autoconf213: not found
- autoconf-2.13
  /bin/sh: autoconf-2.13: not found
- autoconf2.13
  /bin/sh: autoconf2.13: not found
  Waf: Leaving directory `/home/dhruvbird/projects/spidernode/build'
  Build failed:  -> task failed (err #127): 
  {task: libjs_static.a dtoa.c,prmjtime.cpp,jsweakmap.cpp,jsinfer.cpp,jsmath.cpp,jsscope.cpp,jsnum.cpp,jsprobes.cpp,jspropertytree.cpp,jsclone.cpp,jstypedarray.cpp,jsdbgapi.cpp,jsstr.cpp,jsalloc.cpp,jsonparser.cpp,jswrapper.cpp,jskwgen.cpp,jsgc.cpp,jsapi.cpp,jsexn.cpp,jsdhash.cpp,jscompartment.cpp,jsbool.cpp,jsoplengen.cpp,jsgcstats.cpp,jscrashreport.cpp,jsfun.cpp,jsprf.cpp,jsscript.cpp,jsinterp.cpp,jsarray.cpp,jsobj.cpp,jsutil.cpp,jsfriendapi.cpp,jspropertycache.cpp,jsxdrapi.cpp,jsdate.cpp,jsanalyze.cpp,jsproxy.cpp,jswatchpoint.cpp,jsopcode.cpp,jsnativestack.cpp,jsiter.cpp,jshash.cpp,MemoryMetrics.cpp,json.cpp,jscntxt.cpp,jsreflect.cpp,sharkctl.cpp,jsatom.cpp,jslog2.cpp,jsdtoa.cpp,jsxml.cpp,jsgcmark.cpp,jsscriptinlines.h,jsexn.h,jsclone.h,jsstrinlines.h,jsgcstats.h,jsgcinlines.h,jsobj.h,json.h,sharkctl.h,jsval.h,jstypes.h,jsapi.h,jsalloc.h,jsboolinlines.h,jsnum.h,jsinterpinlines.h,jsobjinlines.h,jswatchpoint.h,jsarrayinlines.h,jspropertycache.h,jsinferinlines.h,jsbool.h,jsarray.h,jscrashformat.h,jscell.h,jscntxt.h,jsopcodeinlines.h,jsopcode.h,jsstr.h,prmjtime.h,jstypedarray.h,jsinterp.h,jsfun.h,jsatominlines.h,jsonparser.h,jsfriendapi.h,jsdhash.h,jsweakmap.h,jsproxy.h,jsanalyze.h,jscompat.h,jsnativestack.h,jsprf.h,jstypedarrayinlines.h,jscrashreport.h,jsscope.h,jsinfer.h,jsversion.h,jsscopeinlines.h,jspubtd.h,jsutil.h,jsfuninlines.h,jsxml.h,jswrapper.h,jspropertytree.h,jsdate.h,jsiter.h,jsnuminlines.h,jsgcmark.h,jspropertycacheinlines.h,jsprvtd.h,jslibmath.h,jswin.h,jsdbgapi.h,jsxdrapi.h,jscompartment.h,jsatom.h,jscpucfg.h,jsgc.h,jsreflect.h,jsmath.h,jsscript.h,jscntxtinlines.h,jslock.h,jshash.h,jsdtoa.h,jsprobes.h,jsclass.h,jsclist.h,js-config.in,js-config.h.in,configure.in,Makefile.in,internal.cpp,handles.cpp,function.cpp,core.cpp,string.cpp,array.cpp,objecttemplate.cpp,functiontemplate.cpp,object.cpp,template.cpp,v8.cpp,v8.h,v8-internal.h,v8-debug.h,configure.in,Makefile.in,Assertions.cpp,Attributes.h,GuardObjects.h,MSStdInt.h,RefPtr.h,LinkedList.h,RangedPtr.h,Types.h,Util.h,StdInt.h,Assertions.h,Makefile.in,configure -> libjs_static.a}
  make: **\* [program] Error 1

**Comment by jhford** [comment]
Looks like you need to install autoconf 2.13 to be able to build the mozilla js engine.  You need version 2.13 specifically.

**Comment by jhford** [comment]
Looks like you need to install autoconf 2.13 to be able to build the mozilla js engine.  You need version 2.13 specifically.

**Comment by jhford** [comment]
Looks like you need to install autoconf 2.13 to be able to build the mozilla js engine.  You need version 2.13 specifically.

**Comment by jhford** [comment]
Looks like you need to install autoconf 2.13 to be able to build the mozilla js engine.  You need version 2.13 specifically.

**Comment by jhford** [comment]
Looks like you need to install autoconf 2.13 to be able to build the mozilla js engine.  You need version 2.13 specifically.

**Comment by jhford** [comment]
sigh, thanks github for not showing me that I already posted a comment.
